### ISSUE TITLE
IDT and ODT

### ISSUE THREAD

**Issue by lukeflowers** [thatcherfreeman/aces-transforms#3]
I'm using a few of the IDT and ODT's for some projects. I'm on Metal in DVR 18.1. on Mac OSX 13.2 I'm getting some errors unless I take out the top "DEFINE_ACES_PARAM(IS_PARAMETRIC_ACES_TRANSFORM: 0)" in the DCTL.  Is that okay? It seems to work, but I wasn't sure what that line was there for.

**Comment by thatcherfreeman** [comment]
Where are you installing these DCTLs? As it says in the README, make sure you're installing them in the separate ACES Transforms folder that's within your user directory, not the global LUT folder. Then they'll show up in the ACES Transform tool like they're natively supported by Resolve

**Comment by thatcherfreeman** [comment]
The `DEFINE_ACES_PARAM(IS_PARAMETRIC_ACES_TRANSFORM: 0` is there to make it work with the ACES Transform tool, so I guess your options are to keep that line and put them in the ACES Transform/IDT folder or to put them in your LUT folder and delete that first line

**Comment by lukeflowers** [comment]
I’m putting them in the wrong place….that’s my fault. Sorry about that….thank you for making these!
