### ISSUE TITLE
DaVinci Intermediate IDT/ODT CAT accuracy

### ISSUE THREAD

**Issue by antonmeleshkevich** [thatcherfreeman/aces-transforms#4]
Hi, Thatcher!
I found DaVinci Intermediate IDT/ODT DCTLs give some difference compared to using Bradford CAT from Chromatic Adaptation effect.

Also wouldn't using CAT02 give more expected results?

Here is more about choosing CAT method for DaVinci Wide Gamut: https://community.acescentral.com/t/aces-and-chromatic-adaptation-consistency/5217

These values give the perfect match with CST (which uses CAT02):

```
__CONSTANT__ float matrix[9] = {
     0.748270290270679f,  0.167694659549422f,  0.084035050222766f,
     0.020842123444419f,  1.111904742666049f, -0.132746866104714f,
    -0.091512257422527f, -0.127746712807242f,  1.219258970229265f,
};
// Used inverse of matrix from the IDT.
__CONSTANT__ float matrix[9] = {
     1.328323120016896f, -0.213523641303889f, -0.114799478824335f,
    -0.013160753845427f,  0.912865417908090f,  0.100295335979076f,
     0.098319230930014f,  0.079618463603444f,  0.822062305501921f,
};
```
Calculated using [this](https://www.colour-science.org:8010/apps/rgb_colourspace_transformation_matrix?input-colourspace=DaVinci+Wide+Gamut&output-colourspace=ACES2065-1&chromatic-adaptation-transform=CAT02&formatter=spimtx&decimals=15) calculator, that allows to choose up to 15 decimals, so maybe you'll find it useful.

**Comment by thatcherfreeman** [comment]
I agree that the Resolve CST uses CAT02 adaptation. I'm curious though, from that thread it seemed like ODTs from ACES mostly use Bradford and the IDTs mostly use CAT02. I threw Bradford into that IDT/ODT combo initially because the literature suggested that Bradford performs better in benchmarks, but I do see that it would be more convenient to use CAT02 I suppose. I'd probably have to update all the IDTs and ODTs here though lol. Thoughts?

**Comment by antonmeleshkevich** [comment]
I think, those who know pros and cons of different CATs are more than capable of editing the existing DCTL to use any preferred CAT. And I bet the majority of artists barely know what CAT is. But they can notice the difference between IDT and CST, that will be accumulated with each roundtrip.
So I (who doesn't know what CAT is better and why) prefer CAT02 from the practical point of view.
But it seems to be a lot of work, so I won't dare to tell you redo all IDT/ODT (or better to call them CSC?).
But DWG seems important and widely used, so that one probably could be updated. Or, if you prefer to keep Bradford, maybe it's not enough decimals, that make it to not match with Resolve Chromatic Adaptation effect?

**Comment by thatcherfreeman** [comment]
I agree that there are real benefits in terms of convenience of having my transforms match the CAT used by the CST (which is CAT02), and visually the difference between Bradford and CAT02 is small enough that the workflow benefits of using CAT02 outweighs them. My bradford should match the chromatic adaptation effect, but I'll just switch it to CAT02 in the next day or two and keep you posted.

**Comment by thatcherfreeman** [comment]
Hey Anton, I just switched most of the DCTLs to CAT02, so the davinci intermediate one should match the CST. Thanks for the link to that calculator btw, it's better than the one I was using.

**Comment by antonmeleshkevich** [comment]
Thank you!
