### ISSUE TITLE
N-Log 10 bit code value error

### ISSUE THREAD

**Issue by wenjun-n** [thatcherfreeman/aces-transforms#5]
IDT/Nikon N-Log IDT.dctl

I noticed that in your N-Log IDT file, #line18, #line19, #line20 uses code value of 1024.0f, but 10 bit values ranges from 0.0 to 1023.0 right? So perhaps this is a mistake? I may be wrong, anyways just a heads up.

**Comment by thatcherfreeman** [comment]
Thanks for the catch, I've just updated the IDT and ODT accordingly.
