### ISSUE TITLE
DJI D-Log IDT would not work when ACES RGC is enabled in the project level

### ISSUE THREAD

**Issue by akeybreakyheart** [thatcherfreeman/aces-transforms#6]
Selecting DJI D-Log IDT at the Project and Clip level would not work when ACES RGC is enabled in the project level.

I'm on Apple Silicons (M1 Pro and M2 Pro).

**Comment by thatcherfreeman** [comment]
hey, great catch. I was able to reproduce this and have just pushed a fix, which I tbh don't really understand why it only was broken when the RGC was enabled. Please download a new version of the D-Log IDT and it should work now!
